// SPDX-FileCopyrightText: 2026 CoreWeave, Inc.
// SPDX-License-Identifier: Apache-2.0
// SPDX-PackageName: forge-agent-lens-for-codex

/**
 * Install/uninstall mechanics: write the detach shim and merge our Stop entry
 * into ~/.codex/hooks.json without clobbering anything.
 *
 * hooks.json is array-based per event, so we APPEND our entry and remove only
 * our own hook (not the enclosing group) on uninstall. We refuse to overwrite a
 * corrupt hooks.json, and back it up only once (never clobbering the pristine
 * copy). Our entry is tagged with a stable marker comment so identification
 * survives a changed install path.
 */
import {promises as fs} from 'node:fs';
import {dirname, join} from 'node:path';

import {CODEX_HOOKS_FILE, LOG_FILE, FORGE_CODEX_HOME} from './constants.js';

const HOOK_SHIM_FILE = join(FORGE_CODEX_HOME, 'stop-hook.sh');

/**
 * v1 registers only Stop. SubagentStop would fire a redundant worker on the
 * PARENT rollout (racing the parent's own Stop) — we re-add it when subagent
 * nesting lands and reads the child transcript.
 */
const HOOK_EVENTS = ['Stop'] as const;
const HOOK_TIMEOUT_SEC = 30;
/** Stable identity for our hook, independent of the install path. */
const OWNER_MARKER = 'forge-agent-lens-for-codex-hook';

// The subset of ~/.codex/hooks.json we read and rewrite; unknown keys are preserved on write.
interface HookHandler {
  type: string;
  command: string;
  timeout?: number;
}
interface MatcherGroup {
  matcher?: string;
  hooks: HookHandler[];
}
interface HooksFile {
  hooks?: Record<string, MatcherGroup[]>;
  [key: string]: unknown;
}

/** POSIX single-quote escaping so apostrophes/backslashes in paths can't break the shell. */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/**
 * The hooks.json command. Run via shell (Codex expands `~`). The trailing `#`
 * comment is ignored on execution but gives us a stable marker to match on.
 */
export function hookCommand(): string {
  return `sh ${shellQuote(HOOK_SHIM_FILE)} # ${OWNER_MARKER}`;
}

function shimContents(nodePath: string, collectorJs: string): string {
  return `#!/bin/sh
# forge-agent-lens-for-codex Stop-hook shim (generated by \`forge-agent-lens-for-codex install\`).
# Hands the Stop payload to a fully-detached worker and returns immediately so
# Codex is NEVER blocked. Emits nothing on stdout (a stdout decision payload
# would alter Codex's turn flow).
NODE=${shellQuote(nodePath)}
COLLECTOR=${shellQuote(collectorJs)}
LOG=${shellQuote(LOG_FILE)}
mkdir -p "$(dirname "$LOG")" 2>/dev/null
TMP="$(mktemp "\${TMPDIR:-/tmp}/forge-agent-lens-for-codex.XXXXXX")" || exit 0
cat > "$TMP"
# Detach: background subshell with all fds redirected away from Codex's pipes.
( "$NODE" "$COLLECTOR" "$TMP" >>"$LOG" 2>&1 </dev/null & ) >/dev/null 2>&1
exit 0
`;
}

export async function writeShim(
  nodePath: string,
  collectorJs: string
): Promise<string> {
  await fs.mkdir(FORGE_CODEX_HOME, {recursive: true});
  await fs.writeFile(HOOK_SHIM_FILE, shimContents(nodePath, collectorJs), {
    mode: 0o755,
  });
  return HOOK_SHIM_FILE;
}

interface MergeResult {
  added: string[];
  alreadyPresent: string[];
}

export async function mergeHooks(): Promise<MergeResult> {
  const file = await readHooksFile(); // throws on corrupt JSON → caller aborts without writing
  const command = hookCommand();
  const hooks = (file.hooks ??= {});
  const added: string[] = [];
  const alreadyPresent: string[] = [];

  for (const event of HOOK_EVENTS) {
    const groups = (hooks[event] ??= []);
    if (groups.some(isOurGroup)) {
      alreadyPresent.push(event);
      continue;
    }
    groups.push({
      hooks: [{type: 'command', command, timeout: HOOK_TIMEOUT_SEC}],
    });
    added.push(event);
  }

  if (added.length > 0) {
    await backupHooksFile();
    await writeHooksFile(file);
  }
  return {added, alreadyPresent};
}

export async function removeHooks(): Promise<string[]> {
  let file: HooksFile;
  try {
    file = await readHooksFile();
  } catch {
    return []; // missing or corrupt — nothing safe to do
  }
  if (!file.hooks) return [];

  const removed: string[] = [];
  for (const event of HOOK_EVENTS) {
    const groups = file.hooks[event];
    if (!groups) continue;
    const nextGroups: MatcherGroup[] = [];
    for (const group of groups) {
      const original = group.hooks ?? [];
      const kept = original.filter(h => !isOurHook(h)); // remove only OUR hook
      if (kept.length === original.length) {
        nextGroups.push(group); // untouched
      } else {
        removed.push(event);
        if (kept.length > 0) nextGroups.push({...group, hooks: kept}); // preserve co-located hooks
      }
    }
    if (nextGroups.length > 0) file.hooks[event] = nextGroups;
    else delete file.hooks[event];
  }

  if (removed.length > 0) {
    await backupHooksFile();
    await writeHooksFile(file);
  }
  return removed;
}

export async function hooksInstalled(): Promise<boolean> {
  try {
    const file = await readHooksFile();
    return HOOK_EVENTS.some(e => (file.hooks?.[e] ?? []).some(isOurGroup));
  } catch {
    return false;
  }
}

/** Parse hooks.json without changing it so install can fail before other writes. */
export async function validateHooksFile(): Promise<void> {
  await readHooksFile();
}

function isOurHook(handler: HookHandler): boolean {
  return (
    typeof handler.command === 'string' &&
    handler.command.includes(OWNER_MARKER)
  );
}

function isOurGroup(group: MatcherGroup): boolean {
  return (group.hooks ?? []).some(isOurHook);
}

async function readHooksFile(): Promise<HooksFile> {
  let raw: string;
  try {
    raw = await fs.readFile(CODEX_HOOKS_FILE, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {}; // no file yet — fine
    throw err;
  }
  try {
    return JSON.parse(raw) as HooksFile;
  } catch {
    throw new Error(
      `${CODEX_HOOKS_FILE} is not valid JSON — refusing to overwrite it. Fix or remove it, then re-run.`
    );
  }
}

async function writeHooksFile(file: HooksFile): Promise<void> {
  await fs.mkdir(dirname(CODEX_HOOKS_FILE), {recursive: true});
  await fs.writeFile(CODEX_HOOKS_FILE, JSON.stringify(file, null, 2));
}

async function backupHooksFile(): Promise<void> {
  const backup = `${CODEX_HOOKS_FILE}.bak`;
  try {
    await fs.access(backup);
    return; // a backup already exists; never clobber the pristine copy
  } catch {
    // no backup yet
  }
  try {
    await fs.writeFile(backup, await fs.readFile(CODEX_HOOKS_FILE));
  } catch {
    // nothing to back up
  }
}
